[package]
name = "thermal-printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
escpos = { version = "0.13.1", features = ["barcodes", "codes_2d", "graphics", "serial_port"] }
teloxide = { version = "0.13", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
openssl = "0.10.68"
serialport = "4.6.0"
image = "0.25.4"
